### ISSUE TITLE
Carrier module

### ISSUE THREAD

**Issue by hoodoos** [pgte/fugue#10]
Fugue seem to be dependent on carrier module kind of silently, not a word in docs or someth like that. Is it okay?

**Comment by pgte** [comment]
If you install it through npm you should get carrier also installed.

http://search.npmjs.org/#/fugue

Please see if you are using the latest and node > 0.3.2

**Comment by hoodoos** [comment]
Ah, no I got it from github and currently on 0.3.8. i'm still on 0.2.5 node. Moving to 0.4.0 then, but not ready yet.

**Comment by pgte** [comment]
README instructions tell you install via npm :)
