### ISSUE TITLE
Add main property to package.json

### ISSUE THREAD

**Issue by aflatter** [pgte/fugue#9]
The latest node and npm versions introduced some changes in how packages are handled and thus require('fugue') currently fails.
The problems is that a 'main' property seems to be required now (See https://github.com/isaacs/npm/blob/master/doc/json.md).
Adding `main: "./lib/fugue.js"` fixes this issue.

**Comment by aflatter** [comment]
Same for your carrier module by the way. :-)

**Comment by pgte** [comment]
Done and done :)

**Comment by aflatter** [comment]
Amazing, thanks. :)
